### ISSUE TITLE
dataset availability?

### ISSUE THREAD

**Issue by junaidp1** [nishitanand/Threat_Detection#1]
Hello: thank you for the great work. Any chance of uploading the original dataset? Thanks.

**Comment by nishitanand** [comment]
Hi @junaidp1, thank you for your interest in my project and your kind words. Here is the link for the dataset. It contains training data as obj.zip and testing data as test.zip
https://www.dropbox.com/sh/zwwzusmbxlzf3gh/AADZm1X3tWiMdrrwldRnuv1Ea?dl=0
Have a Nice Day!!

**Comment by junaidp1** [comment]
Awesome. Thanks so much.
